CREATE USER DEVELOP IDENTIFIED BY DEVELOP;

GRANT CREATE SESSION TO DEVELOP;
GRANT UNLIMITED TABLESPACE TO DEVELOP;

GRANT CREATE TABLE TO DEVELOP;

grant CREATE SEQUENCE TO DEVELOP;
--GRANT   DELETE,  INSERT,  SELECT,  UPDATE ON COTIZADOR.DETALLE_INCOMPLETO TO COTIZADOR_WEB WITH GRANT OPTION ;
